bauer_dress/bauer_dress/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop import views as shop_view
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('coupons/', include('django_simple_coupons.urls')),
    path('info/', include('information.urls')),
    path('promo/', include('promotion.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('accounts/', include('allauth.urls')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
    path('', include('shop.urls')),
 ]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'shop.views.error404'
handler500 = 'shop.views.error500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bauer_dress/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('clear/', views.cart_clear, name='cart_clear'),
	path('clear_coupon/', views.cart_clear_coupon, name='clear_coupon'),
	path('add/<product_id>/<price>/<product_set_slug>/', views.cart_add, name='cart_add'),
	path('remove/<product_id>/<price>/<color>/<quantity>/<product_set_slug>/', views.cart_remove, name='cart_remove')
]

bauer_dress/information/urls.py
from django.urls import path
from . import views


app_name = 'info'
urlpatterns = [
    path('privacy/', views.privacy, name='privacy'),
    path('help/', views.help_page, name='help'),
    path('about/', views.about, name='about'),
    path('delivery/', views.delivery, name='delivery'),
    path('FAQ/', views.QuestionListView.as_view(), name='faq'),
    path('FAQ/create/', views.QuestionCreateView.as_view(), name='faq-create'),
    path('admin/response/<question_id>/', views.answerQuestion, name='response'),
]

bauer_dress/shop/urls.py
from django.urls import path
from . import views
from promotion import views as promo_views


app_name = 'shop'
urlpatterns = [
    path('', promo_views.main, name='main'),
    path('dresses/', views.dresses, name='dresses'),
    path('shop/', views.product_list, name='index'),
    path('shop/for-rent/', views.for_rent, name='rent'),
    path('rate/<int:id>/', views.rate_product, name='rate'),
    path('categories/<category_slug>/', views.product_list, name='index_by_category'),
    path('notification/<notification_id>/<order_id>/', views.notification_handler, name='notified_obj'),
    path('tags/<tag_slug>/', views.product_list, name='index_by_tag'),
    path('<category_slug>/<int:id>/<slug>/', views.product_detail, name='details'),
    path('<category_slug>/<int:id>/<slug>/<set_slug>/', views.product_set__detail, name='product_set__detail'),
    path('<int:review_id>/', views.review_response, name='response'),
]

bauer_dress/wishlist/urls.py
from django.urls import path
from . import views


app_name = 'wishlist'
urlpatterns = [
	path('', views.index, name='index'),
	# path('clear/', views.wishlist_clear, name='wishlist_clear'),
	path('cart-add/<product_id>/<price>/<product_set_slug>/', views.cart_add, name='cart_add'),
	path('remove/<product_id>/<price>/<quantity>/<product_set_slug>/', views.wishlist_remove, name='wishlist_remove'),
	path('wishlist-add/<product_id>/<price>/<product_set_slug>/', views.wishlist_add, name='wishlist_add'),
]

bauer_dress/shop/forms.py
from django import forms
from .models import Review, Product, Category, ReviewResponse
import django_filters
from django.db import models


class ReviewForm(forms.Form):
	class Meta:
		model = Review
		fields = ['name', 'review', 'rate']



class ListFilterForm(django_filters.FilterSet):
    rent = django_filters.BooleanFilter(field_name='rent', widget=forms.CheckboxInput)

    class Meta:
        model = Product
        fields = {
            'price_from': ['lt'],
            'price_to': ['gt'],
            'material': ['exact'],
            'tag': ['exact'],
            'category': ['exact']
        }

class CategoryFilterForm(django_filters.FilterSet):
    rent = django_filters.BooleanFilter(field_name='rent', widget=forms.CheckboxInput)

    class Meta:
        model = Product
        fields = {
            'price_from': ['lt'],
            'price_to': ['gt'],
            'material': ['exact'],
            'tag': ['exact']
        }

class ForRentFilterForm(django_filters.FilterSet):

    class Meta:
        model = Product
        fields = {
            'price_from': ['lt'],
            'price_to': ['gt'],
            'material': ['exact'],
            'tag': ['exact'],
            'category': ['exact']
        }


class ReviewResponseForm(forms.ModelForm):
    class Meta:
        model = ReviewResponse
        fields = ['response']

bauer_dress/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Category, Product, Review, Material, Tag, ReviewForm, Size, \
	Tag, ProductSet, SizeSet, ReviewResponse
from django.utils import timezone
from cart.forms import CartAddProductForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from .forms import ListFilterForm, ReviewResponseForm, ForRentFilterForm, CategoryFilterForm
from promotion.models import Promotion
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.http import require_POST
from django.views.decorators.cache import cache_page
from orders.models import Order
from notifications.models import Notification
from django.contrib.auth.models import Group
from notifications.signals import notify
from django.urls import reverse
from django.db.models import Q


@cache_page(60 * 15)
def product_detail(request, id, slug, category_slug):
	product = get_object_or_404(Product, id=id, slug=slug, stock__gt=0)
	cart_product_form = CartAddProductForm()
	review_form = ReviewForm()
	response_form = ReviewResponseForm()
	category = get_object_or_404(Category, slug=category_slug)
	products_with_category_exclude = Product.objects.filter(category=category, stock__gte=1).exclude(id=product.id)[:4]
	if products_with_category_exclude.count() <= 1:
		products_with_category_exclude = None
	
	
	return render(request, 'shop/distribution/detail.html', {'product': product,
														'cart_product_form': cart_product_form,
														'review_form': review_form,
														'response_form': response_form,
														'category': category,
														'category_products': products_with_category_exclude})


@cache_page(60 * 15)
def product_set__detail(request, id, slug, category_slug, set_slug):
	product = get_object_or_404(Product, id=id, slug=slug, stock__gt=0)
	cart_product_form = CartAddProductForm()
	review_form = ReviewForm()
	response_form = ReviewResponseForm()
	category = get_object_or_404(Category, slug=category_slug)
	products_with_category_exclude = Product.objects.filter(category=category, stock__gte=1).exclude(id=product.id)[:5]
	if products_with_category_exclude.count() <= 1:
		products_with_category_exclude = None
	set = get_object_or_404(ProductSet, slug=set_slug)
	size_set = get_object_or_404(SizeSet, size_set=set)
	sets = product.sets.all().exclude(size_set=size_set)
	current_set = product.sets.get(size_set=size_set)



	return render(request, 'shop/distribution/detail_with_set.html', {'product': product,
														'cart_product_form': cart_product_form,
														'review_form': review_form,
														'response_form': response_form,
														'category': category,
														'set': set,
														'sets': sets,
														'current_set': current_set,
														'category_products': products_with_category_exclude})



@cache_page(60 * 15)
def product_list(request, category_slug=None, tag_slug=None):
	category = None
	tag = None
	categories = Category.objects.all()
	products = Product.objects.filter(stock__gt=0).order_by('-updated')
	f = ListFilterForm(request.GET, queryset=products)
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = Product.objects.filter(stock__gt=0, category=category)
		f = CategoryFilterForm(request.GET, queryset=products)

	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		products = Product.objects.filter(stock__gt=0, tag=tag)


	paginator = Paginator(f.qs, 16)
	page_number = request.GET.get('page')

	try:
		page_obj = paginator.get_page(page_number)
	except PageNotAnInteger:
		page_obj = paginator.page(1)
	except EmptyPage:
		page_obj = paginator.page(paginator.num_pages)

	return render(request, 'shop/product/list_shop.html', {
		'page_obj': page_obj,
		'filter': f,
		'category':category,
		'tag': tag,
	})
	
@cache_page(60 * 15)
def dresses(request):
	products = Product.objects.filter(Q(category__name='Повседневные платья') | Q(category__name='Праздничные платья'), stock__gt=0).order_by('-updated')
	f = ListFilterForm(request.GET, queryset=products)


	paginator = Paginator(f.qs, 16)
	page_number = request.GET.get('page')

	try:
		page_obj = paginator.get_page(page_number)
	except PageNotAnInteger:
		page_obj = paginator.page(1)
	except EmptyPage:
		page_obj = paginator.page(paginator.num_pages)

	return render(request, 'shop/product/dresses_list.html', {
		'page_obj': page_obj,
		'filter': f
	})	


@cache_page(60 * 15)
def for_rent(request):
	products = Product.objects.filter(stock__gt=0, rent=True).order_by('-updated')
	f = ForRentFilterForm(request.GET, queryset=products)

	paginator = Paginator(f.qs, 12)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	return render(request, 'shop/product/for_rent_list.html', {
		'page_obj': page_obj,
		'filter': f,
	})


def rate_product(request, id):
	product = get_object_or_404(Product, id=id)
	url = product.get_absolute_url()
	form = ReviewForm(request.POST)
	if form.is_valid():
		user = request.user
		admins = Group.objects.get(name='staff')
		cd = form.cleaned_data
		if cd['rating']:
			review = Review.objects.create(user=request.user, product=product, name=cd['name'], review=cd['review'], rate=cd['rating'])
		else:
			review = Review.objects.create(user=request.user, product=product, name=cd['name'], review=cd['review'], rate=0)
		review.save()
		messages.success(request, message='Ваш отзыв опубликован. Спасибо!')
		notify.send(user, recipient=admins, verb=f'Добавлен отзыв для {product.name} (звезда: {review.rate})')

	return redirect(url)



def error404(request, *args, **kwargs):
	return render(request, 'shop/404.html')

def error500(request, *args, **kwargs):
	return render(request, 'shop/500.html')


def cheap_product_list(request):
	# promotion = None
	products = Product.objects.filter(stock__gt=0).order_by('price')
	# if slug:
	# 	promotion = get_object_or_404(Promotion, slug=slug)
	# 	products= Product.objects.filter(stock__gt=0, promo__promotion=promotion).order_by('price')
	f = ListFilterForm(request.GET, queryset=products)



	paginator = Paginator(f.qs, 12)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)


	return render(request, 'shop/product/list_shop.html', {
		'products': products,
		'page_obj': page_obj,
		'filter': f,
	})



def expensive_product_list(request):
	# promotion = None
	products = Product.objects.filter(stock__gt=0).order_by('-price')
	# if slug:
	# 	promotion = get_object_or_404(Promotion, slug=slug)
	# 	products= Product.objects.filter(stock__gt=0, promo__promotion=promotion).order_by('-price')
	f = ListFilterForm(request.GET, queryset=products)



	paginator = Paginator(f.qs, 12)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)

	return render(request, 'shop/product/list_shop.html', {
		'products': products,
		'page_obj': page_obj,
		'filter': f,
	})




def new_products(request):
	products = []
	product_list = Product.objects.filter(stock__gt=0)
	for product in product_list:
		if product.status_new():
			products.append(product)
		else:
			continue
	
	return render(request, 'shop/product/list_shop.html', {
		'products': products,
	})


@staff_member_required
def review_response(request, review_id):
	review = Review.objects.get(pk=review_id)
	url = request.META['HTTP_REFERER']
	if request.method == 'POST':
		form = ReviewResponseForm(request.POST)
		if form.is_valid():
			ReviewResponse.objects.create(user=request.user, review=review, response=form.cleaned_data['response'])
	messages.success(request, message='Ответ опубликован!')
	return redirect(url)

@staff_member_required
def notification_handler(request, notification_id, order_id=None):
	order = None
	if not order_id:
		order = get_object_or_404(Order, id=order_id)
		coupon = order.coupon
	notification = get_object_or_404(Notification, id=notification_id)
	notification.mark_as_read()
	url = request.META["HTTP_REFERER"]

	if order:
		return render(request, 'admin/orders/order/detail.html', {'order': order, 'url': url})
	else:
		return redirect(url)

bauer_dress/shop/templates/shop/account_nav.html
{% load static %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'cart:cart_detail' %}">
      <i class="fas fa-dolly-flatbed mr-1 text-gray"></i>Корзина
      <small class="text-gray">
        {% if cart %}
          {% with total_items=cart|length %}
            ({{ total_items }})
          {% endwith %}
        {% else %}
          (0)
        {% endif %}
      </small>
    </a>
  </li>
  {% if user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'wishlist:index' %}">
      <i class="far fa-heart mr-1"></i>
      <small class="text-gray">
        {% if wishlist.items.all %}
          ({{ wishlist.items.all|length }})
        {% else %}
          (0)
        {% endif %}
      </small>
    </a>
  </li>
  {% endif %}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-user-alt mr-1 text-gray"></i>
      Аккаунт
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="right: 0;left: auto;">
      {% if user.is_authenticated %}
      {% if user.is_staff %}
      <a class="dropdown-item" href="{% url 'notifications:all' %}">
        Уведомления
      </a>
      <div class="dropdown-divider"></div>
      {% endif %}
      <a class="dropdown-item" href="{% url 'account_email' %}">Настройка E-mail</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'account_logout' %}">
        Выйти
      </a>
      {% else %}
      <a class="dropdown-item" href="{% url 'account_login' %}">
        Вход
      </a>
      <a class="dropdown-item" href="{% url 'account_signup' %}">
        Регистрация
      </a>
      {% endif %}
    </div>
  </li>
  {% if user.is_staff %}
  {% if unread_count %}
  <li class="nav-item dropdown">
    <a class="nav-link" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      {% live_notify_badge badge_class="badge bg-dark text-white" %}
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="right: 0;left: auto;">

      {% with objects=user.notifications.unread %}
      {% for notification in objects %}
      <a class="dropdown-item" href="{% url 'shop:notified_obj' notification.id notification.action_object %}">
        {{ notification.verb }}
      </a>
      <div class="dropdown-divider"></div>
      {% endfor %}
      {% endwith %}

    </div>
  </li>
  {% endif %}
  {% endif %}
</ul>

bauer_dress/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% block seo %}
        {% block main %}
          
        {% endblock %}

        {% block product %}
          
        {% endblock %}

        {% block promo %}
          
        {% endblock %}

        {% block category %}
          
        {% endblock %}

        {% block new %}
          
        {% endblock %}
    {% endblock %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'shop/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- cookiealert styles -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Wruczek/Bootstrap-Cookie-Alert@gh-pages/cookiealert.css">
    <!-- Lightbox-->
    <link rel="stylesheet" href="{% static 'shop/vendor/lightbox2/css/lightbox.min.css' %}">
    <!-- Bootstrap select-->
    <link rel="stylesheet" href="{% static 'shop/vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
    <!-- Owl Carousel-->
    <link rel="stylesheet" href="{% static 'shop/vendor/owl.carousel2/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'shop/vendor/owl.carousel2/assets/owl.theme.default.css' %}">
    <!-- Google fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'shop/css/style.blue.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet -->
    <link rel="stylesheet" href="{% static 'shop/css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'shop/img/favicon.png' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <div class="page-holder bg-light">
      <!-- navbar-->
      {% include 'shop/nav.html' %}
      <!-- Main Wrapper start -->
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

      {% block content %}
      {% endblock %}
      <div class="alert text-center cookiealert" role="alert">
          <b>Вам нравятся cookies?</b> &#x1F36A; Мы используем файлы cookie, чтобы вам было удобнее пользоваться нашим сайтом. <a href="https://cookiesandyou.com/" target="_blank">Узнать больше</a>

          <button type="button" class="btn btn-primary btn-sm acceptcookies">
              Принимаю
          </button>
      </div>
      <footer class="bg-dark text-white">
        <div class="container py-4">
          <div class="row py-5">
            <div class="col-md-4 mb-3 mb-md-0">
              <h6 class="text-uppercase mb-3">Помощь</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="{% url 'info:delivery' %}">Доставка</a></li>
                <li><a class="footer-link" href="{% url 'info:help' %}">Что-то не так с товаром?</a></li>
                <li><a class="footer-link" href="{% url 'info:privacy' %}">Конфиденциальность</a></li>
              </ul>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
              <h6 class="text-uppercase mb-3">О нас</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="{% url 'info:faq-create' %}">Задать вопрос</a></li>
                <li><a class="footer-link" href="{% url 'info:about' %}">Наша Story</a></li>
                <li><a class="footer-link" href="{% url 'info:faq' %}">Ответы на вопросы</a></li>
              </ul>
            </div>
            <div class="col-md-4">
              <h6 class="text-uppercase mb-3">Контакты</h6>
              <ul class="list-unstyled mb-0">
                <li><a class="footer-link" href="https://www.instagram.com/bauerdress/" target="_blank">Instagram</a></li>
                <li><a class="footer-link" href="tel:+89833022013">+8 (983) 302-20-13</a></li>
                <li><a class="footer-link" href="mailto:bauergallla@gmail.com">bauergallla@gmail.com</a></li>
              </ul>
            </div>
          </div>
          <div class="border-top pt-4" style="border-color: #1d1d1d !important">
            <div class="row">
              <div class="col-lg-6">
                <p class="small text-muted mb-0">&copy; 2020 BAUER DRESS</p>
              </div>
              <div class="col-lg-6 text-lg-right">
                <p class="small text-muted mb-0">designed by <a class="text-white reset-anchor" href="https://bootstraptemple.com/p/bootstrap-ecommerce" target="_blank">Ondrej</a></p>
              </div>
            </div>
          </div>
        </div>
      </footer>
      <!-- JavaScript files-->

      <!-- Include cookiealert script -->
      <script src="https://cdn.jsdelivr.net/gh/Wruczek/Bootstrap-Cookie-Alert@gh-pages/cookiealert.js"></script>

      <script src="{% static 'shop/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'shop/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'shop/vendor/lightbox2/js/lightbox.min.js' %}"></script>
      <script src="{% static 'shop/vendor/nouislider/nouislider.min.js' %}"></script>
      <script src="{% static 'shop/vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
      <script src="{% static 'shop/vendor/owl.carousel2/owl.carousel.min.js' %}"></script>
      <script src="{% static 'shop/vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

      <script src="{% static 'shop/js/front.js' %}"></script>
      <script>        
        // ------------------------------------------------------- //
        //   Inject SVG Sprite - 
        //   see more here 
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {
        
            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function(e) {
            var div = document.createElement("div");
            div.className = 'd-none';
            div.innerHTML = ajax.responseText;
            document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
        // this is set to BootstrapTemple website as you cannot 
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('{% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}/media/orion-svg-sprite.svg'); 
        
      </script>
      <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </div>
  </body>
</html>

bauer_dress/shop/templates/shop/in_process.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<main class="main-content-wrapper">
    <div class="error-area pt--50 pt-xl--70 pb--120 pb-xl--100 pb-lg--95 pb-sm--90">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8 text-center">
                    <div class="error">
                        <h1>Sorry!</h1>
                        <h2>Данная страница находится в работе</h2>
                        <a href="{% url 'shop:index' %}" class="btn">На Главную</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

bauer_dress/shop/templates/shop/nav.html
<!-- navbar-->
<header class="header bg-white">
  <div class="container px-0 px-lg-3">
    <nav class="navbar navbar-expand-lg navbar-light py-3 px-lg-0"><a class="navbar-brand" href="{% url 'shop:main' %}"><span class="font-weight-bold text-uppercase text-dark">Bauer Dress</span></a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!-- <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:main' %}">Главная</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:index' %}">Магазин</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:rent' %}">Аренда платьев</a>
          </li>
          <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="pagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Контакты</a>
            <div class="dropdown-menu mt-3" aria-labelledby="pagesDropdown">
              <a class="dropdown-item border-0 transition-link" href="https://www.instagram.com/bauerdress/" target="_blank">Instagram</a>
              <a class="dropdown-item border-0 transition-link" href="mailto:bauergallla@gmail.com">bauergallla@gmail.com</a>
              <a class="dropdown-item border-0 transition-link" href="tel:+89833022013">+8 (983) 302-20-13</a>
            </div>
          </li>
        </ul>
        {% include 'shop/account_nav.html' %}
      </div>
    </nav>
  </div>
</header>