bauer_dress/bauer_dress/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop import views as shop_view
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('coupons/', include('django_simple_coupons.urls')),
    path('info/', include('information.urls')),
    path('promo/', include('promotion.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('accounts/', include('allauth.urls')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
    path('', include('shop.urls')),
 ]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'shop.views.error404'
handler500 = 'shop.views.error500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bauer_dress/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('clear/', views.cart_clear, name='cart_clear'),
	path('clear_coupon/', views.cart_clear_coupon, name='clear_coupon'),
	path('add/<product_id>/<price>/<product_set_slug>/', views.cart_add, name='cart_add'),
	path('remove/<product_id>/<price>/<color>/<quantity>/<product_set_slug>/', views.cart_remove, name='cart_remove')
]

bauer_dress/information/urls.py
from django.urls import path
from . import views


app_name = 'info'
urlpatterns = [
    path('privacy/', views.privacy, name='privacy'),
    path('help/', views.help_page, name='help'),
    path('about/', views.about, name='about'),
    path('delivery/', views.delivery, name='delivery'),
    path('FAQ/', views.QuestionListView.as_view(), name='faq'),
    path('FAQ/create/', views.QuestionCreateView.as_view(), name='faq-create'),
    path('admin/response/<question_id>/', views.answerQuestion, name='response'),
]

bauer_dress/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    
    path('thank-you/<int:order_id>/', views.thank_you, name='thank_you'),
    path('finish/', views.finish, name='finish'),
    path('bad-results/', views.bad_results, name='bad_results'),
    path('order/<int:order_id>/', views.admin_order_detail,
    							name='admin_order_detail'),
    path('order/<int:order_id>/pdf/', views.admin_order_pdf,
    							name='admin_order_pdf'),
]

bauer_dress/shop/urls.py
from django.urls import path
from . import views
from promotion import views as promo_views


app_name = 'shop'
urlpatterns = [
    path('', promo_views.main, name='main'),
    path('dresses/', views.dresses, name='dresses'),
    path('shop/', views.product_list, name='index'),
    path('shop/for-rent/', views.for_rent, name='rent'),
    path('rate/<int:id>/', views.rate_product, name='rate'),
    path('categories/<category_slug>/', views.product_list, name='index_by_category'),
    path('notification/<notification_id>/<order_id>/', views.notification_handler, name='notified_obj'),
    path('tags/<tag_slug>/', views.product_list, name='index_by_tag'),
    path('<category_slug>/<int:id>/<slug>/', views.product_detail, name='details'),
    path('<category_slug>/<int:id>/<slug>/<set_slug>/', views.product_set__detail, name='product_set__detail'),
    path('<int:review_id>/', views.review_response, name='response'),
]

bauer_dress/orders/models.py
from django.db import models
from shop.models import Product, ProductSet
from django import forms
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from django_simple_coupons.models import Coupon
import json


class Order(models.Model):

	PENDING = 'pending'
	WAITING_FOR_CAPTURE = 'waiting_for_capture'
	SUCCEEDED = 'succeeded'
	CANCELED = 'canceled'

	STATUS_CHOICES = (
		(PENDING, 'В процессе'),
		(WAITING_FOR_CAPTURE, 'В процессе подтверждения'),
		(SUCCEEDED, 'Принято'),
		(CANCELED, 'Отменено'),
	)

	paid = models.BooleanField(default=False, verbose_name='Оплачено')
	first_name = models.CharField(max_length=50, verbose_name='Имя')
	last_name = models.CharField(max_length=50, verbose_name='Фамилия')
	address = models.CharField(max_length=200, verbose_name='Адрес')
	phone = models.CharField(max_length=14, verbose_name='Тел.')
	email = models.EmailField(null=False, blank=False)
	created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
	updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
	dilivery_method = models.CharField(max_length=1, blank=False, verbose_name='Доставка')
	comment = models.CharField(max_length=200, blank=False, null=True, verbose_name='Мерки')
	coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL,
	                                related_name='orders',
	                                null=True,
	                                blank=True,
	                                verbose_name='Купон')
	payment_id = models.CharField(max_length=1000, verbose_name='ID Платежа')
	status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=PENDING, verbose_name='Статус')

	class Meta:
		ordering = ('created',)
		verbose_name = 'заказ'
		verbose_name_plural = 'заказы'


	def __str__(self):
		return 'Order {}'.format(self.id)

	def get_total_cost(self):
	    return sum(item.get_cost() for item in self.items.all())


	def get_total(self):
		if self.coupon:
			if self.dilivery_method == '1':
				return self.coupon.get_discounted_value(self.get_total_cost())
			elif self.dilivery_method == '2':
				return self.coupon.get_discounted_value(self.get_total_cost(), 270)
			elif self.dilivery_method == '3':
				return self.coupon.get_discounted_value(self.get_total_cost())
			elif self.dilivery_method == '4':
				return self.coupon.get_discounted_value(self.get_total_cost(), 350)
			else:
				return self.coupon.get_discounted_value(self.get_total_cost())
		else:
			item_sum = sum(item.get_cost() for item in self.items.all())
			if self.dilivery_method == '1':
				return item_sum
			elif self.dilivery_method == '2':
				return item_sum + Decimal(270)
			elif self.dilivery_method == '3':
				return item_sum
			elif self.dilivery_method == '4':
				return item_sum + Decimal(350)
			else:
				return item_sum


class OrderItem(models.Model):
	
	order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
	product_set = models.ForeignKey(ProductSet, on_delete=models.SET_NULL, null=True, related_name='order_item_product_sets')
	price = models.DecimalField(max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')
	size = models.CharField(max_length=50, default="", verbose_name='Размер')
	color = models.CharField(max_length=100, default="", verbose_name='Цвет')
	
	def __str__(self):
		return '{}'.format(self.id)

	def get_cost(self):
		return self.price * self.quantity
		

bauer_dress/orders/forms.py
from django import forms
from .models import Order

#

class OrderCreateForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ['first_name', 'last_name', 'email', 'address', 'phone', 'dilivery_method', 'comment']

bauer_dress/orders/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from cart.cart import Cart
from .models import OrderItem, Order
from .forms import OrderCreateForm
from shop.models import Product
from django.contrib.admin.views.decorators import staff_member_required
from django_simple_coupons.forms import CouponApplyForm
import weasyprint
from asgiref.sync import async_to_sync
from django.core.mail import send_mail
from email_sub.models import Subscription
from django.core.exceptions import ObjectDoesNotExist
from .tasks import order_created
from notifications.signals import notify
from django.contrib.auth.models import Group
from decimal import Decimal
from yookassa import Payment
import uuid
from django.urls import reverse


def bad_results(request):
	return render(request, 'orders/order/created_bad.html')

def finish(request):
	return render(request, 'orders/order/created.html')

def thank_you(request, order_id):
	cart = Cart(request)
	order = Order.objects.get(pk=order_id)
	payment = Payment.find_one(order.payment_id)
	if payment.paid == True:
		idempotence_key = str(uuid.uuid4())
		response = Payment.capture(
		  order.payment_id,
		  {
		    "amount": {
		      "value": Decimal(order.get_total()),
		      "currency": "RUB"
		    }
		  },
		  idempotence_key
		)
		order.paid = True
		for item in order.items.all():
			if item.product.can_spend:
				if item.product.stock >= item.quantity:
					item.product.stock -= item.quantity
					item.product.save()
				else:
					pass
			else:
				pass
		order.save()
		cart.clear()
		if cart.coupon:
			cart.clear_coupon()
		return redirect('orders:finish')
	else:
		return redirect('orders:bad_results')



def order_create(request):
	cart = Cart(request)
	user = request.user
	admins = Group.objects.get(name='staff')
	coupon_apply_form = CouponApplyForm()
	if request.method == 'POST':
		form = OrderCreateForm(request.POST)
		if form.is_valid():
			order = form.save(commit=False)
			if cart.coupon:
			    order.coupon = cart.coupon
			    order.discount = cart.coupon.discount.value
			order.save()
			for item in cart:
				OrderItem.objects.create(order=order,
										product=item['product'],
										product_set=item['product_set'],
										price=item['price'],
										quantity=item['quantity'],
										size = item['product_set'].size_set,
										color = item['color'])
			try:
				Subscription.objects.get(email=order.email)
			except ObjectDoesNotExist:
				Subscription.objects.create(name=order.first_name, surname=order.last_name, email=order.email)
			###

			idempotence_key = str(uuid.uuid4())
			payment = Payment.create({
			    "amount": {
			      "value": str(order.get_total()),
			      "currency": "RUB"
			    },
			    "payment_method_data": {
			      "type": "bank_card"
			    },
			    "confirmation": {
			      "type": "redirect",
			      "return_url": "https://f67cc52b570c.ngrok.io{}".format(reverse('orders:thank_you', args=[order.id]))
			    },
			    "description": "Заказ №%s" % order.id
			}, idempotence_key)
			order.payment_id = payment.id
			order.save()

			# get confirmation url
			confirmation_url = payment.confirmation.confirmation_url
			####

			#clearing cart and coupon
			notify.send(admins, recipient=admins, action_object=order, verb=f'Заказ #{order.id}')
			order_created.delay(order.id)
			return redirect(confirmation_url)
	else:
		form = OrderCreateForm()
	return render(request, 'orders/order/create_v2.html', {'cart': cart,
														'form': form,
														'coupon_apply_form': coupon_apply_form})

@staff_member_required
def admin_order_detail(request, order_id):
	order = get_object_or_404(Order, id=order_id)
	coupon = order.coupon
	
	return render(request, 'admin/orders/order/detail.html', {'order': order})



@staff_member_required
def admin_order_pdf(request, order_id):
	order = get_object_or_404(Order, id=order_id)
	html = loader.render_to_string('orders/order/pdf.html', {'order': order})
	response = HttpResponse(content_type='application/pdf')
	response['Content-Disposition'] = 'filename=\
									"order_{}.pdf"'.format(order.id)
	weasyprint.HTML(
		string=html
		).write_pdf(response,
			stylesheets=[weasyprint.CSS(str(settings.STATIC_ROOT) + '/css/pdf.css')])
	return response 

bauer_dress/orders/templates/orders/order/create_v2.html
{% extends 'shop/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block seo %}
    <title>Оформление заказа | Bauer Dress</title>
{% endblock %}
{% block content %}
	<div class="container">
    <!-- HERO SECTION-->
    <section class="py-5 bg-light">
      <div class="container">
        <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
          <div class="col-lg-6">
            <h1 class="h2 text-uppercase mb-0">Оформление заказа</h1>
          </div>
          <div class="col-lg-6 text-lg-right">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                <li class="breadcrumb-item"><a href="{% url 'shop:main' %}">Главная</a></li>
                <li class="breadcrumb-item"><a href="{% url 'cart:cart_detail' %}">Корзина</a></li>
                <li class="breadcrumb-item active" aria-current="page">Оформление</li>
                <li class="breadcrumb-item">Спасибо</li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>
    <section class="py-5">
      <!-- BILLING ADDRESS-->
      <h2 class="h5 text-uppercase mb-4">Адрес доставки</h2>
      <div class="row">
        <div class="col-lg-8">
          <form method="POST" action="{% url 'orders:order_create' %}">
          	{% csrf_token %}
  			    {% for hidden in form.hidden_fields %}
  			      {{ hidden }}
  			    {% endfor %}
            <div class="row">
              <div class="col-lg-6 form-group">
                <label class="text-small text-uppercase" for="{{ field.id_for_label }}">Имя</label>
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field form.first_name class="form-control form-control-lg is-invalid" placeholder="Введите Ваше имя" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                              {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.first_name class="form-control form-control-lg is-valid" placeholder="Введите Ваше имя" %}
                    {% endif %}
                {% else %}
                    {% render_field form.first_name class="form-control form-control-lg " placeholder="Введите Ваше имя" %}
                {% endif %}
              </div>
              <div class="col-lg-6 form-group">
                <label class="text-small text-uppercase" for="{{ field.id_for_label }}">Фамилия</label>
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field form.last_name class="form-control form-control-lg is-invalid" placeholder="Введите Вашу фамилию" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                              {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.last_name class="form-control form-control-lg is-valid" placeholder="Введите Вашу фамилию" %}
                    {% endif %}
                {% else %}
                    {% render_field form.last_name class="form-control form-control-lg " placeholder="Введите Вашу фамилию" %}
                {% endif %}
              </div>
              <div class="col-lg-6 form-group">
                <label class="text-small text-uppercase" for="{{ field.id_for_label }}">Email адрес</label>
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field form.email class="form-control form-control-lg is-invalid" placeholder="example@company.com" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                              {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.email class="form-control form-control-lg is-valid" placeholder="example@company.com" %}
                    {% endif %}
                {% else %}
                    {% render_field form.email class="form-control form-control-lg " placeholder="example@company.com" %}
                {% endif %}
              </div>
              <div class="col-lg-6 form-group">
                <label class="text-small text-uppercase" for="{{ field.id_for_label }}">Телефон</label>
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field form.phone class="form-control form-control-lg is-invalid" placeholder="79000000000" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                              {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.phone class="form-control form-control-lg is-valid" placeholder="79000000000" %}
                    {% endif %}
                {% else %}
                    {% render_field form.phone class="form-control form-control-lg " placeholder="79000000000" %}
                {% endif %}
              </div>
              <div class="col-lg-12 form-group">
                <label class="text-small text-uppercase" for="{{ field.id_for_label }}">Адрес</label>
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field form.address class="form-control form-control-lg is-invalid" placeholder="г. Новосибирск, ул.Тургенева 5 кв.70, 630050" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                              {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.address class="form-control form-control-lg is-valid" placeholder="г. Новосибирск, ул.Тургенева 5 кв.70, 630050" %}
                    {% endif %}
                {% else %}
                    {% render_field form.address class="form-control form-control-lg " placeholder="г. Новосибирск, ул.Тургенева 5 кв.70, 630050" %}
                {% endif %}
              </div>
              <div class="col-lg-12 form-group">
			          <label class="text-small text-uppercase" for="{{ field.id_for_label }}">Тип доставки</label>
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field form.dilivery_method class="form-control form-control-lg is-invalid" placeholder="Выберите" style='font-size:16px;' %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                              {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="">
          								<select class="form-control custom-select is-invalid" id="id_dilivery_method" style="font-size: 16px;" name="dilivery_method">
                            <option selected>Выберите...</option>
                            <option value="1">Самовывоз</option>
                            <option value="2">Почтой (270 руб.)</option>
                            <option value="3">Доставка по Нск (бесплатно)*</option>
                            <option value="4">Курьер по Нск (350 руб.)*</option>
          								</select>
          							</div>
                    {% endif %}
                {% else %}
                    <div class="">
        							<select class="custom-select form-control" id="id_dilivery_method" style="font-size: 16px;" name="dilivery_method">
        							    <option selected>Выберите...</option>
        							    <option value="1">Самовывоз</option>
        							    <option value="2">Почтой (270 руб.)</option>
        							    <option value="3">Доставка по Нск (бесплатно)*</option>
                          <option value="4">Курьер по Нск (350 руб.)*</option>
        							</select>
        						</div>
                {% endif %}  
              </div>
              <div class="col-lg-12 form-group">
                <label class="text-small text-uppercase" for="{{ field.id_for_label }}">Мерки</label>
                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field form.comment class="form-control form-control-lg is-invalid" placeholder="напр. Рост-175, грудь-80" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                              {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field form.comment class="form-control form-control-lg is-valid" placeholder="напр. Рост-175, грудь-80" %}
                    {% endif %}
                {% else %}
                    {% render_field form.comment class="form-control form-control-lg " placeholder="напр. Рост-175, грудь-80" %}
                {% endif %}
              </div>        
              <div class="col-lg-8 form-group">
                <button class="btn btn-dark" type="submit">Оформить</button>
              </div>
            </div>
          </form>
          <p class="text-muted text-small">* бесплатно - в 10км от центра, далее но не более 30 км - курьер</p>
          <p class="text-muted text-small">** нажимая кнопку "Оформить" вы соглашаетесь с нашей <a href="{% url 'info:privacy' %}">Политикой Конфиденциальности.</a></p>
        </div>
        <!-- ORDER SUMMARY-->
        <div class="col-lg-4">
          <div class="card border-0 rounded-0 bg-light">
            <div class="card-body">
              <h5 class="text-uppercase mb-4">Ваш заказ</h5>
              <ul class="list-unstyled mb-0">
              	{% for item in cart %}
                {% with product=item.product %}
                  <li class="d-flex align-items-center justify-content-between">
                    <div>
                    	<strong class="small font-weight-bold">{{ item.product.name }} <span>&#10005;</span>{{ item.quantity }}</strong>
                      <span class="text-small text-muted">({{ item.product_set.size_set }})</span>
                  	</div>
                    <span class="text-muted small">{{ item.total_price }}{% if product.rent %} руб/{% if product.pay_method %}{{ product.pay_method }}{% else %}ч{% endif %}{% else %} руб.{% endif %}</span>
                  </li>
                  <li class="border-bottom my-2"></li>
                {% endwith %}
                {% endfor %}
                {% if cart.coupon %}
                <li class="d-flex align-items-center justify-content-between">
                  <div>
                    <strong class="text-uppercase small font-weight-bold">Купон</strong>
                    <span class="text-small text-muted">({{ cart.coupon.code }})</span>
                  </div>

                  <span class="text-muted small">
                    - {% if cart.coupon.discount.is_percentage %}{{ cart.coupon.discount.value }}%{% else %}{{ cart.coupon.discount.value }} руб.{% endif %}
                  </span>
                </li>
                {% endif %}
                <li class="d-flex align-items-center justify-content-between mt-2"><strong class="text-uppercase small font-weight-bold">Итого {% if cart.coupon %}(- {{ cart.get_discounted_value }} руб.){% endif %}*</strong><span>{{ cart.get_total_price_after_discount|floatformat:'2' }} руб.</span></li>
              </ul>
              <p class="text-muted text-small mt-2">* цена без учета доставки</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}

bauer_dress/orders/templates/orders/order/created.html
{% extends 'shop/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block seo %}
  <title>Спасибо за покупку! | Интернет-магазин Bauer Dress</title>
  <meta name="description" content=""/>
{% endblock %}
{% block content %}
	<div class="container">
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Спасибо</h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="{% url 'shop:index' %}">Главная</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'cart:cart_detail' %}">Корзина</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'orders:order_create' %}">Оформление</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Спасибо</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>
        <section class="py-5">
          <!-- BILLING ADDRESS-->
          <h2 class="h5 text-uppercase mb-4">Заказ #{{ order.id }}</h2>
          <h5>Проверьте Ваш почтовый ящик, который вы указали при оформлении заказа, и сверьте заказ!</h5>
        </section>
    </div>
{% endblock %}

bauer_dress/orders/templates/orders/order/created_bad.html
{% extends 'shop/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block seo %}
  <title>Не получилось! | Интернет-магазин Bauer Dress</title>
  <meta name="description" content=""/>
{% endblock %}
{% block content %}
	<div class="container">
        <!-- HERO SECTION-->
        <section class="py-5 bg-light">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Упс...</h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="{% url 'shop:index' %}">Главная</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'cart:cart_detail' %}">Корзина</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'orders:order_create' %}">Оформление</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Ошибка</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>
        <section class="py-5">
          <!-- BILLING ADDRESS-->
          <h2 class="h5 text-uppercase mb-4">Что-то не так</h2>
          <h5>Если вы не отменяли платеж, то свяжитесь с нами, мы все решим!</h5>
        </section>
    </div>
{% endblock %}

bauer_dress/orders/templates/orders/order/pdf.html
<html>
	<body>
		<h1>Bauer Dress</h1>
		<p>
			Заказ №{{ order.id }}</br>
			<span class="secondary">
				{{ order.created }}
			</span>
		</p>
		<h3>Счет для:</h3>
		<p>
			{{ order.first_name }} {{ order.last_name }}<br>
			{{ order.email }}<br>
			{{ order.address }}<br>
		</p>
		<h3>Куплено</h3>
		<table>
			<thead>
                <tr>
                    <th>Товар</th>
                    <th>Цена</th>
                    <th style="white-space: nowrap;">Кол-во</th>
                    <th>Размер</th>
                    <th>Цвет</th>
                    <th>Итого</th>
                </tr>
                </thead>
			<tbody>
                {% for item in order.items.all %}
                    <tr class="row{% cycle '1' '2' %}">
                        <td>{{ item.product.name }}{% if item.product.rent %} (аренда){% endif %}</td>
                        <td style="white-space: nowrap;" class="num">{{ item.price }}{% if item.product.rent %} руб/{% if item.product.pay_method %}{{ item.product.pay_method }}{% else %}ч{% endif %}{% else %} руб.{% endif %}</td>
                        <td class="num">{{ item.quantity }}</td>
                        <td class="num">{{ item.size }}</td>
                        <td class="num">{{ item.color }}</td>
                        <td style="white-space: nowrap;" class="num">{{ item.get_cost }} руб.</td>
                    </tr>
                {% endfor %}
                {% if order.coupon %}
                <tr class="coupon">
                    <td colspan="3">Купон ({{ order.coupon.code }}) {% if order.coupon.discount.is_percentage %} -{{ order.coupon.discount.value }}%{% else %} -{{ order.coupon.discount.value }} руб.{% endif %}</td>
                </tr>
                {% endif %}
                
                <tr class="total">
                    <td colspan="1"><strong>Доставка:</strong></td>
                    {% if order.dilivery_method == '1' %}
                        <td colspan="3">Самовывоз</td>
                    {% elif order.dilivery_method == '3' %}
                        <td colspan="3">Бесплатно</td>
                    {% elif order.dilivery_method == '4' %}
                        <td colspan="3">Курьер (350 руб.)</td>
                    {% else %}
                        <td colspan="3">Почта (270.00 Р) </td>
                    {% endif %}
                </tr>
                <tr class="total">
                    <td colspan="3"><strong>К оплате</strong></td>
                    <td style="white-space: nowrap;" class="num"><strong>{{ order.get_total }} руб.</strong></td>
                </tr>
            </tbody>
		</table>
		<span class="{% if order.paid %}paid{% else %}pending{% endif %}">
		{% if order.paid %}<span style="color: green;">Оплачено</span>{% else %}В процессе оплаты{% endif %}
		</span>
	</body>
</html>