bauer_dress/bauer_dress/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop import views as shop_view
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('coupons/', include('django_simple_coupons.urls')),
    path('info/', include('information.urls')),
    path('promo/', include('promotion.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('accounts/', include('allauth.urls')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
    path('', include('shop.urls')),
 ]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler404 = 'shop.views.error404'
handler500 = 'shop.views.error500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bauer_dress/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('clear/', views.cart_clear, name='cart_clear'),
	path('clear_coupon/', views.cart_clear_coupon, name='clear_coupon'),
	path('add/<product_id>/<price>/<product_set_slug>/', views.cart_add, name='cart_add'),
	path('remove/<product_id>/<price>/<color>/<quantity>/<product_set_slug>/', views.cart_remove, name='cart_remove')
]

bauer_dress/shop/urls.py
from django.urls import path
from . import views
from promotion import views as promo_views


app_name = 'shop'
urlpatterns = [
    path('', promo_views.main, name='main'),
    path('dresses/', views.dresses, name='dresses'),
    path('shop/', views.product_list, name='index'),
    path('shop/for-rent/', views.for_rent, name='rent'),
    path('rate/<int:id>/', views.rate_product, name='rate'),
    path('categories/<category_slug>/', views.product_list, name='index_by_category'),
    path('notification/<notification_id>/<order_id>/', views.notification_handler, name='notified_obj'),
    path('tags/<tag_slug>/', views.product_list, name='index_by_tag'),
    path('<category_slug>/<int:id>/<slug>/', views.product_detail, name='details'),
    path('<category_slug>/<int:id>/<slug>/<set_slug>/', views.product_set__detail, name='product_set__detail'),
    path('<int:review_id>/', views.review_response, name='response'),
]

bauer_dress/wishlist/urls.py
from django.urls import path
from . import views


app_name = 'wishlist'
urlpatterns = [
	path('', views.index, name='index'),
	# path('clear/', views.wishlist_clear, name='wishlist_clear'),
	path('cart-add/<product_id>/<price>/<product_set_slug>/', views.cart_add, name='cart_add'),
	path('remove/<product_id>/<price>/<quantity>/<product_set_slug>/', views.wishlist_remove, name='wishlist_remove'),
	path('wishlist-add/<product_id>/<price>/<product_set_slug>/', views.wishlist_add, name='wishlist_add'),
]

bauer_dress/shop/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.utils import timezone
from django.utils import timezone
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
import datetime
from decimal import Decimal
from ckeditor.fields import RichTextField


class SeoModel(models.Model):
    seo_title = models.CharField('SEO Название', blank=True, max_length=250)
    seo_description = models.CharField('SEO Описание', blank=True, max_length=250)

    def get_seo_title(self):
        if self.seo_title:
            return self.seo_title
        return ''

    def get_seo_description(self):
        if self.seo_description:
            return self.seo_description
        return ''

    class Meta:
        abstract = True


class Category(SeoModel):
	"""
	Product's category model
	"""
	name = models.CharField(max_length=200, db_index=True, verbose_name=u"Название",
		help_text='В мн.ч')
	slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name=u"Название (лат.)")


	class Meta:
		ordering=('name',)
		verbose_name = 'тип товара'
		verbose_name_plural = 'типы товаров'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:index_by_category', args=[self.slug])


class Material(models.Model):
	name = models.CharField('Материал', max_length=50)
	slug = models.SlugField(max_length=200, unique=True, null=True, verbose_name=u"Название (лат.)")



	def __str__(self):
		return self.name

	class Meta:
		verbose_name='материал'
		verbose_name_plural = 'материалы'

	def get_absolute_url(self):
		return reverse('shop:index_by_material', kwargs={'material_slug': self.slug})


class Tag(models.Model):
	name = models.CharField(max_length=50, blank=False, verbose_name='Название')
	slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name=u"Название (лат.)")

	class Meta:
		verbose_name = 'возраст'
		verbose_name_plural = 'возрасты' 

	def __str__(self):
		return self.name	


	def get_absolute_url(self):
		return reverse('shop:index_by_tag', kwargs={'tag_slug': self.slug})



class Product(models.Model):
	"""
	Product model
	"""
	category = models.ForeignKey(Category, related_name='products', 
		on_delete=models.SET_NULL, null=True, verbose_name=u"Тип товара")
	name = models.CharField(max_length=200, db_index=True, verbose_name=u"Название")
	slug = models.SlugField(max_length=200, db_index=True, verbose_name=u"URL", 
		help_text='То как этот товар будет отображен в URL.')
	description = RichTextField(default='Full description of product', blank=False, null=True, verbose_name=u"Описание",
		help_text='Добавьте полное описание товара, без характеристик.')
	material = models.ForeignKey(Material, on_delete=models.SET_NULL, null=True, verbose_name=u"Материал")
	price_from = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=u"Цена от", blank=False, null=True)
	price_to = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=u"Цена до", blank=False, null=True)
	stock = models.PositiveIntegerField(default=1, verbose_name=u"В наличии (кол-во)")
	can_spend = models.BooleanField(default=False, verbose_name=u"Вычитать со склада")
	created = models.DateTimeField(auto_now_add=True, verbose_name=u"Создан")
	updated = models.DateTimeField(auto_now=True, verbose_name=u"Обновлен")
	tag = models.ForeignKey(Tag, on_delete=models.SET_NULL, null=True, verbose_name='Возраст')
	rent = models.BooleanField("Доступно в аренду (если да, заполни ниже)", default=False)
	pay_method = models.CharField("Если аренда, то какая оплата?", blank=True, null=True, max_length=3, help_text='Если почасовая-ч, по дням-д, неделям-нед.')

	
	def __str__(self):
		return self.name

	class Meta:
		index_together = (('id','slug'),)
		verbose_name = 'товар'
		verbose_name_plural = 'товары'

	# def get_price(self):
	#     return Decimal(self.price - self.price * (self.discount / Decimal('100')))


	def status_new(self):
		now = timezone.now()
		if now + datetime.timedelta(days=-5) < self.created < now:
			return True
		else:
			return False


	def get_absolute_url(self):
		return reverse('shop:details', args=[self.category.slug, self.id, self.slug])


	def get_review_count(self):
		review_count = 0
		for review in self.reviews.all():
			review_count += 1
		return review_count

	def get_rating_tag(self):
		rating_sum = 0 #collect all ratings and after all i will divide it
		reviews_counter = 0
		average_rating_tag = 'zero'
		if self.reviews.all():
			for review in self.reviews.all():
				reviews_counter += 1
				rating_sum += review.rate
			average_rating = int(rating_sum / reviews_counter)
			if average_rating == 0:
				average_rating_tag = 'zero'
			if average_rating == 1:
				average_rating_tag = 'one'
			if average_rating == 2:
				average_rating_tag = 'two'
			if average_rating == 3:
				average_rating_tag = 'three'
			if average_rating == 4:
				average_rating_tag = 'four'
			if average_rating == 5:
				average_rating_tag = 'five'
			return average_rating_tag
		return average_rating_tag




class Gallery(models.Model):
    """
    Model for Product which allow to add much photos
    """

    image = models.ImageField(upload_to='gallery', verbose_name='Фото')
    alt = models.CharField('Описание картинки', max_length=30, blank=False, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')

    class Meta:
    	verbose_name = 'фото товара'
    	verbose_name_plural = 'фото товаров'



class SizeSet(models.Model):

	def __str__(self):
		return '{0}-{1}'.format(self.sizes.filter().first(), self.sizes.filter().last())
	
	class Meta:
		verbose_name = 'сет размеров'
		verbose_name_plural = 'сеты размеров'


class Size(models.Model):
	size = models.CharField(max_length=50, null=True)
	size_set = models.ForeignKey(SizeSet, on_delete=models.CASCADE, null=True, related_name='sizes')

	def __str__(self):
		return self.size



class Color(models.Model):
	name = models.CharField('Цвет', default='', max_length=100)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'цвет'
		verbose_name_plural = 'цвета'

class Colors(models.Model):
	color = models.ForeignKey(Color, on_delete=models.SET_NULL, null=True)
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, related_name='colors')



class ProductSet(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='sets')
	size_set = models.ForeignKey(SizeSet, on_delete=models.SET_NULL, null=True, related_name='size_set')
	price = models.DecimalField(max_digits=10, decimal_places=2, blank=False, verbose_name=u"Цена")
	slug = models.SlugField(max_length=300, unique=True, db_index=True)

	class Meta:
		verbose_name = 'сет товара'
		verbose_name_plural = 'сеты товаров'

	def __str__(self):
		return 'Сет {0} {1} {2}'.format(self.product.name, self.size_set, self.price)


	def get_absolute_url(self):
		return reverse('shop:product_set__detail', args=[self.product.category.slug, self.product.id, self.product.slug, self.slug])



class Review(models.Model):
	"""
	Review models
	"""
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Пользователь')
	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews', verbose_name='Товар')
	name = models.CharField(max_length=30, blank=False, verbose_name='Имя')
	review = models.CharField(max_length=350, default='', blank=False, null=False, verbose_name='Отзыв')
	rate = models.PositiveIntegerField(default=1, blank=False, null=False, verbose_name='Рейтинг')
	created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
	updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
	avatar = models.ImageField(default='default.png', upload_to='avatars/', verbose_name='Аватар')

	# def get_queryset(self):
	# 	return self.product.reviews.all()[:5]

	def __str__(self):
		return self.name
	class Meta:
		verbose_name = 'отзыв'
		verbose_name_plural = 'отзывы'
		ordering = ('-created',)

	def get_review_rate_tag(self):
		rating_tag = 'zero'
		if self.rate == 0:
			rating_tag = 'zero'
		if self.rate == 1:
			rating_tag = 'one'
		if self.rate == 2:
			rating_tag = 'two'
		if self.rate == 3:
			rating_tag = 'three'
		if self.rate == 4:
			rating_tag = 'four'
		if self.rate == 5:
			rating_tag = 'five'
		return rating_tag


class ReviewResponse(models.Model):
	review = models.ForeignKey(Review, on_delete=models.CASCADE, null=True, verbose_name='Отзыв', related_name='responses')
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Отвечающий')
	response = models.TextField(blank=False, null=True, verbose_name='Ответ')
	created = models.DateTimeField(auto_now_add=True, blank=False, null=True, verbose_name='Создано')
	updated = models.DateTimeField(auto_now=True, blank=False, null=True, verbose_name='Обновлено')

	def __str__(self):
		return 'ответ для {}'.format(self.review.name)

	class Meta:
		verbose_name = 'ответ на отзыв'
		verbose_name_plural = 'ответы на отзывы'


class ReviewForm(ModelForm):
	"""
	Form for reviews
	"""
	ratings = [(i , str(i)) for i in range(1, 6)]
	rating = forms.TypedChoiceField(choices=ratings, coerce=int, widget=forms.RadioSelect())
	class Meta:
		model = Review
		fields = ['name', 'review']
		widgets = {
            'review': forms.Textarea(),
        }

bauer_dress/wishlist/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product
from shop.models import Color, SizeSet, ProductSet

class Wishlist(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')

	def __str__(self):
		return self.user.username

	class Meta:
		verbose_name='лист желаний'
		verbose_name_plural='лист желаний'


class WishlistItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, verbose_name='товар')
	wishlist = models.ForeignKey(Wishlist, on_delete=models.CASCADE, related_name='items')
	price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
	# size_set = models.ForeignKey(SizeSet, on_delete=models.SET_NULL, null=True, related_name='wish_size_set')
	product_set = models.ForeignKey(ProductSet, on_delete=models.SET_NULL, null=True, related_name='product_set')
	date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
	quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')
	status_bought = models.BooleanField("Добавлен в корзину", default=False)

	class Meta:
		verbose_name='желание'
		verbose_name_plural='желания'

	def get_cost(self):
		return self.price * self.quantity

bauer_dress/wishlist/forms.py
from django import forms
from .models import WishlistItem
from shop.models import Color, Size



colors = [('{}'.format(color.name), '{}'.format(color.name)) for color in Color.objects.all()]

class WishlistAddProductForm(forms.Form):
	quantity = forms.IntegerField()
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
	color = forms.TypedChoiceField(choices=colors)

bauer_dress/wishlist/views.py
from django.shortcuts import render, get_object_or_404, redirect
from shop.models import Product
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Wishlist, WishlistItem
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.http import require_POST
# from .forms import WishlistForm
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from shop.models import SizeSet, ProductSet, Product
from cart.cart import Cart
@login_required
def index(request):
	try:
		wishlist = Wishlist.objects.get(user=request.user)
	except ObjectDoesNotExist:
		wishlist = Wishlist.objects.create(user=request.user)
	cart_product_form = CartAddProductForm()
	return render(request, 'wishlist/wishlist.html', {'wishlist': wishlist,
				'cart_product_form': cart_product_form})


@login_required
def wishlist_add(request, product_id, price, product_set_slug):

	wishlist = Wishlist.objects.get(user=request.user)
	product_set = get_object_or_404(ProductSet, slug=product_set_slug)
	# size_set = get_object_or_404(SizeSet, size_set=set)
	product = get_object_or_404(Product, id=product_id)
	url = request.META.get('HTTP_REFERER')
	wishlist_items = None
	try:
		wishlist_items = wishlist.items.get(product=product, price=price, product_set=product_set)
	except ObjectDoesNotExist:
		pass

	if wishlist_items in wishlist.items.all():
		wishlist_items = wishlist.items.get(product=product, price=price, product_set=product_set)
		wishlist_items.quantity +=1
		wishlist_items.save()
	else:
		wishlist_items = wishlist.items.create(product=product, price=price, product_set=product_set)
	messages.success(request, message='Товар успешно добавлен в Желания!')
	return redirect(url)
@login_required
def wishlist_remove(request, product_id, price, quantity, product_set_slug):
	url = request.META.get('HTTP_REFERER')
	product_set = get_object_or_404(ProductSet, slug=product_set_slug)
	# size_set = get_object_or_404(SizeSet, size_set=set)
	wishlist = Wishlist.objects.get(user=request.user)
	product = get_object_or_404(Product, id=product_id)
	wishlist_items = wishlist.items.get(product=product, price=price, product_set=product_set, quantity=quantity).delete()
	messages.success(request, message='Товар успешно удален из Желаний!')
	return redirect(url)



@require_POST
def cart_add(request, product_id, price, product_set_slug):
	cart = Cart(request)
	url = request.META['HTTP_REFERER']
	product = get_object_or_404(Product, id=product_id)
	product_set = get_object_or_404(ProductSet, slug=product_set_slug)
		
	#mark product in wishlist as bought
	try:
		wishlist = Wishlist.objects.get(user=request.user)
	except:
		wishlist = None
		wishlist_item = None
	if wishlist:
		try:
			wishlist_item = wishlist.items.get(product=product, price=price, product_set=product_set)
			wishlist_item.status_bought = True
			wishlist_item.save()
		except ObjectDoesNotExist:
			wishlist_item = None

	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		if wishlist_item:
			cart.add(product=product, quantity=cd['quantity'], init_price=wishlist_item.price, product_set_slug=product_set.slug, color=cd['color'], update_quantity=cd['update'])
		else:
			cart.add(product=product, quantity=cd['quantity'], init_price=price, product_set_slug=product_set.slug, color=cd['color'], update_quantity=cd['update'])
		messages.success(request, message='Товар добавлен в Корзину!')
	return redirect(url)

bauer_dress/wishlist/templates/wishlist/wishlist.html
{% extends 'shop/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block seo %}
    <title>Желания | Bauer Dress</title>
    <meta name="description" content="Нашли что хотели, но нет возможности заказать сейчас? Добавьте товар в Желания"/>
{% endblock %}
{% block content %}
    <div class="container">
        <!-- HERO SECTION-->
        <section class="bg-light" style="padding-top: 3em;">
          <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
              <div class="col-lg-6">
                <h1 class="h2 text-uppercase mb-0">Мои желания</h1>
              </div>
              <div class="col-lg-6 text-lg-right">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb justify-content-lg-end mb-0 px-0">
                    <li class="breadcrumb-item"><a href="{% url 'shop:main' %}">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Желания</li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </section>
        <section class="py-5">
          {% if not wishlist.items.all %}
          <h2 class="h5 text-uppercase mb-4">Лист желаний пуст</h2>
          {% endif %}
          <div class="row">
            {% if wishlist.items.all %}
            <div class="col-lg-12 mb-4 mb-lg-0">
              <!-- CART TABLE-->
              <div class="table-responsive mb-4">
                <table class="table">
                  <thead class="bg-light">
                    <tr>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Товар</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase" style="white-space: nowrap;">Кол-во
                        </strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Цвет</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Размер</strong></th>
                      <th class="border-0" scope="col"> <strong class="text-small text-uppercase">Цена</strong></th>
                      <th class="border-0" scope="col"> </th>
                      <th class="border-0" scope="col"> </th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in wishlist.items.all %}
                    {% with product=item.product %}
                    <form method="POST" action="{% url 'wishlist:cart_add' product.id item.get_cost item.product_set.slug %}">
                      {% csrf_token %}
                      {% for hidden_field in cart_product_form.hidden_fields %}
                        {{ hidden_field }}
                      {% endfor %}
                      {% if cart_product_form.non_field_errors %}
                        <div class="alert alert-danger" role="alert">
                          {% for error in cart_product_form.non_field_errors %}
                            {{ error }}
                          {% endfor %}
                        </div>
                      {% endif %}
                      <tr>
                        <th class="pl-0 border-0" scope="row">
                          <div class="media align-items-center">
                            <a class="reset-anchor d-block animsition-link" href="{{ item.product_set.get_absolute_url }}">
                              <img src="{% if product.images.first %}{{ product.images.first.image.url }}{% else %}{% endif %}" alt="{{ product.images.first.alt }}" width="70"/>
                            </a>
                            <div class="media-body ml-3" style="min-width: 150px;">
                              <strong class="h6">
                                <a class="reset-anchor animsition-link" href="{{ item.product_set.get_absolute_url }}">{{ product.name }}</a>
                              </strong>
                            </div>
                          </div>
                        </th>
                        <td class="align-middle border-0">
                          <div class="quantity">
                            <a class="dec-btn" style="padding: 10px;cursor: pointer;"><i class="fas fa-caret-left"></i></a>
                            <input class="form-control border-0 shadow-0 p-0 text-gray" type="text" value="{{ item.quantity }}" name="quantity" style="background-color: transparent;" id="quantity">
                            <a class="inc-btn" style="padding: 10px;cursor: pointer;"><i class="fas fa-caret-right"></i></a>
                          </div>
                        </td>
                        <td class="align-middle border-0">
                          {% render_field cart_product_form.color class="form-control product-size-variation-btn b-rad--none w200 form-control custom-select" style='width: auto;padding-right: 1.75rem;font-size:16px;' %}
                        </td>
                        <td class="align-middle border-0">
                          <p class="mb-0 small">{{ item.product_set.size_set }}</p>
                        </td>
                        <td class="align-middle border-0">
                          <p class="mb-0 small">{{ item.get_cost }}{% if product.rent %} руб/{% if product.pay_method %}{{ product.pay_method }}{% else %}ч{% endif %}{% else %} руб.{% endif %}</p>
                        </td>
                        <td class="align-middle border-0">
                          <button class="btn btn-dark" style="white-space: nowrap;" type="submit">
                            В корзину
                          </button>
                        </td>
                        <td class="align-middle border-0">
                          <a class="reset-anchor" href="{% url 'wishlist:wishlist_remove' product.id item.price item.quantity item.product_set.slug %}"><i class="fas fa-trash-alt small text-muted"></i></a>
                        </td>
                      </tr>
                    </form>
                    {% endwith %}
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
            <div class="bg-light px-4 py-3">
              <div class="row align-items-center text-center">
                <div class="col-md-6 mb-3 mb-md-0 text-md-left" style="padding-left: 5px;white-space: nowrap;">
                  <a class="btn btn-outline-dark btn-sm" href="{{ request.META.HTTP_REFERER }}"><i class="fas fa-long-arrow-alt-left mr-2"></i>Назад
                  </a>
                </div>
              </div>
            </div>
            {% else %}
            <div class="bg-light px-4 py-3">
              <div class="row align-items-center text-center">
                <div class="col-md-6 mb-3 mb-md-0 text-md-left" style="padding-left: 5px;white-space: nowrap;">
                  <a class="btn btn-outline-dark btn-sm" href="{% url 'shop:index' %}"><i class="fas fa-long-arrow-alt-left mr-2"></i>Назад
                  </a>
                </div>
              </div>
            </div>
            {% endif %}
          </div>
        </section>
    </div>
{% endblock %}